### ISSUE TITLE
v4 doesn't compile with Go 1.4.2

### ISSUE THREAD

**Issue by R4CHI7** [go-redis/redis#370]
v3 used to work great with Go 1.4.2.
I need to use some features in v4 but it doesn't compile with Go 1.4.2

Gives the following error:

`gopkg.in/redis.v4/internal/errors/errors.go:61: undefined: strings.LastIndexByte`

**Comment by vmihailenco** [comment]
Fixed because fix is trivial, but really we support only last 2 Go versions - 1.6 and 1.7.

**Comment by R4CHI7** [comment]
wow that was quick! Thanks! :+1:
